from django.urls import path
from .views import (
    home, citizen_login, citizen_register, citizen_panel,
    citizen_profile, citizen_pass, citizen_update, logout,
    register_vaccine_part1, register_baby,
    load_districts, load_subdistricts, load_healthcare_centers,
    notification, generate_birth_certificate,volunteer_login,volunteer_panel,admin_login,
    district_dashboard,subdistrict_dashboard,add_healthcare_center,
    view_healthcare, edit_healthcare, delete_healthcare,
    manage_volunteers, add_volunteer, edit_volunteer, delete_volunteer,
    police_verification, update_verification,
    admin_logout,volunteer_profile,about,
    passport_verification, update_passport_verification, generate_passport,
    print_passport_list, mark_passport_printed, generate_passport_pdf,
    get_passport_data, view_reports,district_reports,delete_subdistrict_admin,
    edit_subdistrict_admin,manage_subdistrict_admins,process_payment, update_vaccine
    ,monthly_report,manage_police_admins,edit_police_admin,delete_police_admin, get_applicant_details,
    police_change_password,show_passport,add_vaccine,manage_vaccines,edit_vaccine,delete_vaccine,get_vaccine,
    )
from .nid import(
    nid_application,
    nid_application_existing,
    check_birth_certificate,
    view_nid_applications,
    update_nid_status,
    verification_management,
    update_verification_status,
    generate_nid,
    download_nid,
    check_application_status,
    update_face_photo,
    face_verification,
    search_nid
)
from .passport import(
    process_payment,
    pay_fees,
    passport_application,
    update_passport_face_photo, 
    passport_face_verification,
   
    
)

from .allowance import (
    allowance_application,
    verify_allowance_eligibility,
    submit_allowance_application,
    manage_allowance_requests,
    approve_allowance,
    reject_allowance,
)
app_name =  'citizen'

urlpatterns = [
    path('', home, name='index'),
    path('login/', citizen_login, name='citizen_login'),
    path('register/', citizen_register, name='citizen_register'),
    path('panel/', citizen_panel, name='citizen_panel'),
    path('profile/', citizen_profile, name='citizen_profile'),
    path('pass/', citizen_pass, name='citizen_pass'),
    path('citizen_update/', citizen_update, name='citizen_update'),
    path('logout/', logout, name='logout'),
    path('register_vaccine_part1/', register_vaccine_part1, name='register_vaccine_part1'),
    path('register_baby/', register_baby, name='register_baby'),
    path('load_districts/', load_districts, name='load_districts'),
    path('load_subdistricts/', load_subdistricts, name='load_subdistricts'),
    path('load_healthcare_centers/', load_healthcare_centers, name='load_healthcare_centers'),
    path('notification/', notification, name='notification'),
    path('generate_birth_certificate/', generate_birth_certificate, name='generate_birth_certificate'),
    path('volunteer/', volunteer_login, name='volunteer_login'),
    path('volunteer/panel/', volunteer_panel, name='volunteer_panel'),
    path('volunteer/update-vaccine/', update_vaccine, name='update_vaccine'),
    path('volunteer/monthly-report/', monthly_report, name='monthly_report'),

    path('admins/login/', admin_login, name='admin_login'),
    path('admins/district/', district_dashboard, name='district_dashboard'),
    path('admins/sub-district/', subdistrict_dashboard, name='subdistrict_dashboard'),
    path('panel/nid',nid_application, name='nid_application'),
    path('admins/sub-district/add-healthcare/', add_healthcare_center, name='add_healthcare_center'),
    path('admins/sub-district/view-healthcare/', view_healthcare, name='view_healthcare'),
    path('admins/sub-district/edit-healthcare/<int:center_id>/', edit_healthcare, name='edit_healthcare'),
    path('admins/sub-district/delete-healthcare/<int:center_id>/', delete_healthcare, name='delete_healthcare'),
    path('admins/sub-district/manage-volunteers/', manage_volunteers, name='manage_volunteers'),
    path('admins/sub-district/add-volunteer/', add_volunteer, name='add_volunteer'),
    path('admins/sub-district/edit-volunteer/<int:volunteer_id>/', edit_volunteer, name='edit_volunteer'),
    path('admins/sub-district/delete-volunteer/<int:volunteer_id>/', delete_volunteer, name='delete_volunteer'),
    path('admins/sub-district/view-nid/', view_nid_applications, name='view_nid_applications'),
    path('admins/sub-district/nid-application/<int:application_id>/update-status/', update_nid_status, name='update_nid_status'),
    path('admins/sub-district/verifications/', verification_management, name='verification_management'),
    path('admins/sub-district/verification/<int:verification_id>/update-status/', update_verification_status, name='update_verification_status'),
    path('admins/sub-district/verification/<int:verification_id>/generate-nid/', generate_nid, name='generate_nid'),
    path('panel/nid/check-birth-certificate/', check_birth_certificate, name='check_birth_certificate'),
    path('panel/passport/application/', passport_application, name='passport_application'),  

    path('panel/track-status/', check_application_status, name='track_status'),
    path('panel/nid/download/', download_nid, name='download_nid'),  
    path('panel/nid/application-existing/', nid_application_existing, name='nid_application_existing'),
    path('volunteer/profile/',volunteer_profile, name='volunteer_profile'),
    
    path('admins/district/passport/police-verification/', police_verification, name='police_verification'),
    path('panel/passport/verify/', passport_verification, name='passport_verification'),
    path('panel/passport/print-list/', print_passport_list, name='print_passport_list'),
    path('admins/district/print-passport/<int:verification_id>/', 
         mark_passport_printed, 
         name='mark_passport_printed'),    path('admins/logout/', admin_logout, name='admin_logout'),
    path('admins/passport/verification/', passport_verification, name='passport_verification'),
    path('admins/district/passport/update-verification/', update_verification, name='update_verification'),  
    path('admins/passport/update/<int:verification_id>/', update_passport_verification, name='update_passport_verification'),
    path('admins/passport/generate/<int:verification_id>/', generate_passport, name='generate_passport'),
    path('admins/passport/print/<int:verification_id>/', mark_passport_printed, name='mark_passport_printed'),
    path('admins/passport/pdf/<int:verification_id>/', generate_passport_pdf, name='generate_passport_pdf'),
    path('admins/passport/data/<int:verification_id>/', 
         get_passport_data, 
         name='get_passport_data'),   
    path('about/', about, name='about'),
    path('admins/sub-district/reports/', view_reports, name='view_reports'),
    path('passport/verification/<int:verification_id>/face/', 
         passport_face_verification, 
         name='passport_face_verification'),
    path('passport/verification/<int:verification_id>/update-face/', 
        update_passport_face_photo, 
         name='update_passport_face_photo'),
    path('admins/police/get-applicant-details/<str:tracking_number>/', 
      get_applicant_details, 
     name='get_applicant_details'),
    path('admins/police/search-nid/', search_nid, name='search_nid'),
    path('admins/passport/show/<int:verification_id>/', show_passport, name='show_passport'),
    path('admins/district/manage-police-admins/', manage_police_admins, name='manage_police_admins'),
    path('admins/district/edit-police-admin/<int:admin_id>/',edit_police_admin, name='edit_police_admin'),
    path('admins/district/delete-police-admin/<int:admin_id>/',delete_police_admin, name='delete_police_admin'),
    path('admins/district/reports/', district_reports, name='district_reports'),
    # urls.py
    path('panel/passport/pay-fees/', pay_fees, name='pay_fees'),

    path('admins/district/manage-subdistrict-admins/', manage_subdistrict_admins, name='manage_subdistrict_admins'),
    path('admins/district/edit-subdistrict-admin/<int:admin_id>/', edit_subdistrict_admin, name='edit_subdistrict_admin'),
    path('admins/district/delete-subdistrict-admin/<int:admin_id>/', delete_subdistrict_admin, name='delete_subdistrict_admin'),
    path('panel/passport/process-payment/<str:tracking_number>/',  process_payment,  name='process_payment'),
    path('admins/sub-district/verification/<int:verification_id>/update-face/', update_face_photo, name='update_face_photo'),
    path('verification/<int:verification_id>/face/', face_verification, 
         name='face_verification'),
    path('admins/police/change-password/', police_change_password, name='police_change_password'),
    # path('volunteer/', volunteer_login, name='volunteer_login'),
    # path('volunteer/panel/', volunteer_panel, name='volunteer_panel'),
    path('admins/manage-vaccines/', manage_vaccines, name='manage_vaccines'),
    path('admins/add-vaccine/', add_vaccine, name='add_vaccine'),
    path('admins/edit-vaccine/<int:vaccine_id>/', edit_vaccine, name='edit_vaccine'),
    path('admins/delete-vaccine/<int:vaccine_id>/', delete_vaccine, name='delete_vaccine'),
   
    path('admins/get-vaccine/<int:vaccine_id>/', get_vaccine, name='get_vaccine'),

    path('panel/allowance/', allowance_application, name='allowance_application'),
    path('panel/allowance/verify/', verify_allowance_eligibility, name='verify_allowance_eligibility'),
    path('panel/allowance/submit/', submit_allowance_application, name='submit_allowance_application'),
    path('allowance/manage/', manage_allowance_requests, name='manage_allowance_requests'),
    path('allowance/approve/', approve_allowance, name='approve_allowance'),
    path('allowance/reject/', reject_allowance, name='reject_allowance'),
    # path('allowance-account/', allowance_account_view, name='allowance_account'),
    # path('submit-payment-details/<int:application_id>/', submit_payment_details, name='submit_payment_details'),
    # path('manage-allowance-payments/', manage_allowance_payments, name='manage_allowance_payments'),
    # path('process-allowance-payment/', process_allowance_payment, name='process_allowance_payment'),





]
