# Generated by Django 4.0.4 on 2025-02-10 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='healthcare_center_id',
            new_name='healthcare_center',
        ),
        migrations.AddField(
            model_name='nidverification',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nid_faces/', verbose_name='Face Photo'),
        ),
        migrations.AddField(
            model_name='passportverification',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_faces/', verbose_name='Face Photo'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Division', 'Division'), ('District', 'District'), ('Sub district', 'Sub district'), ('Police', 'Police')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('volunteer', 'healthcare_center', 'month')},
        ),
        migrations.CreateModel(
            name='BkashNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.district')),
            ],
            options={
                'db_table': 'bkash_numbers',
            },
        ),
    ]
